name: Build and Publish Flutter Web to GitHub Pages
on: 
  workflow_dispatch:
  push:
    branches: [main, master]
jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /roomie/
